#!/bin/bash

# Required:
# - toilet - http://manpages.ubuntu.com/manpages/bionic/man1/toilet.1.html
#   - if you don't want this remove lines 27, 28 and 29
# - xcowsay - http://manpages.ubuntu.com/manpages/bionic/man6/xcowsay.6.html
#   - if you don't want this remove line 35

wp core download

read -p 'Database name: ' dbname
read -p 'Database user: ' dbuser
read -sp 'Database password: ' dbpass
echo
echo Thank you. Your config file is being created.

wp config create --dbname=$dbname --dbuser=$dbuser --dbpass=$dbpass

read -p 'Site title: ' title
read -p 'Site url: ' url
read -p 'Admin user: ' admin
read -p 'Admin email: ' email
read -sp 'Admin password: ' password

wp core install --url=$url --title=$title --admin_user=$admin --admin_password=$password --admin_email=$email

toilet -f mono9 -F gay Release
toilet -f mono9 -F gay the
toilet -f mono12 -F gay Kraken

echo 'Do you want to release the Kraken? [yes/no]'
read seeadmin;

if [ "$seeadmin" = "yes" ];
    then xcowsay Hi, I will be your Kraken today! :\)
    wp admin
    else echo "Oki doki, then. Have a wonderful day!"
fi
